version: '2'
services:
  db: 
    image: postgres
  web:
    build: .
    command: npm start
    volumes:
      - ".:/home/app/app"
      - "/home/app/chat/node_modules"
    ports:
      - "3000:3000"
    depends_on:
      - db
